// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: 7dc4d5d85c
// Version Date: 2018年 5月28日 星期一 22时12分59秒 UTC

package handlers

import (
	pb "hello-gokit/pb"
)

// HelloV1 implements Service.
func HelloV1(IdHelloV1 int64) (*pb.Req, error) {
	request := pb.Req{
		Id: IdHelloV1,
	}
	return &request, nil
}
