// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hello.proto

package hello

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/tuneinc/truss/deftree/googlethirdparty"

import (
	context "golang.org/x/net/context"
	newcontext "context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Req struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Req) Reset()         { *m = Req{} }
func (m *Req) String() string { return proto.CompactTextString(m) }
func (*Req) ProtoMessage()    {}
func (*Req) Descriptor() ([]byte, []int) {
	return fileDescriptor_hello_69f5b5c287bf80ed, []int{0}
}
func (m *Req) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Req.Unmarshal(m, b)
}
func (m *Req) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Req.Marshal(b, m, deterministic)
}
func (dst *Req) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Req.Merge(dst, src)
}
func (m *Req) XXX_Size() int {
	return xxx_messageInfo_Req.Size(m)
}
func (m *Req) XXX_DiscardUnknown() {
	xxx_messageInfo_Req.DiscardUnknown(m)
}

var xxx_messageInfo_Req proto.InternalMessageInfo

func (m *Req) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Resp struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Resp) Reset()         { *m = Resp{} }
func (m *Resp) String() string { return proto.CompactTextString(m) }
func (*Resp) ProtoMessage()    {}
func (*Resp) Descriptor() ([]byte, []int) {
	return fileDescriptor_hello_69f5b5c287bf80ed, []int{1}
}
func (m *Resp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resp.Unmarshal(m, b)
}
func (m *Resp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resp.Marshal(b, m, deterministic)
}
func (dst *Resp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resp.Merge(dst, src)
}
func (m *Resp) XXX_Size() int {
	return xxx_messageInfo_Resp.Size(m)
}
func (m *Resp) XXX_DiscardUnknown() {
	xxx_messageInfo_Resp.DiscardUnknown(m)
}

var xxx_messageInfo_Resp proto.InternalMessageInfo

func (m *Resp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Resp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*Req)(nil), "hello.Req")
	proto.RegisterType((*Resp)(nil), "hello.Resp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HelloClient is the client API for Hello service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HelloClient interface {
	HelloV1(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Resp, error)
}

type helloClient struct {
	cc *grpc.ClientConn
}

func NewHelloClient(cc *grpc.ClientConn) HelloClient {
	return &helloClient{cc}
}

func (c *helloClient) HelloV1(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Resp, error) {
	out := new(Resp)
	err := c.cc.Invoke(ctx, "/hello.Hello/HelloV1", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HelloServer is the server API for Hello service.
type HelloServer interface {
	HelloV1(newcontext.Context, *Req) (*Resp, error)
}

func RegisterHelloServer(s *grpc.Server, srv HelloServer) {
	s.RegisterService(&_Hello_serviceDesc, srv)
}

func _Hello_HelloV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloServer).HelloV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hello.Hello/HelloV1",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloServer).HelloV1(ctx, req.(*Req))
	}
	return interceptor(ctx, in, info, handler)
}

var _Hello_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hello.Hello",
	HandlerType: (*HelloServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HelloV1",
			Handler:    _Hello_HelloV1_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hello.proto",
}

func init() { proto.RegisterFile("hello.proto", fileDescriptor_hello_69f5b5c287bf80ed) }

var fileDescriptor_hello_69f5b5c287bf80ed = []byte{
	// 210 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0xce, 0xb1, 0x4a, 0x04, 0x31,
	0x10, 0xc6, 0x71, 0x76, 0x73, 0x51, 0x9c, 0x05, 0x91, 0x80, 0x70, 0x5c, 0x75, 0xa4, 0xba, 0x42,
	0x36, 0xa8, 0x8d, 0xbd, 0x8d, 0x75, 0x0a, 0xfb, 0xbd, 0xcd, 0x98, 0x0d, 0xec, 0x65, 0x72, 0xc9,
	0x6c, 0x61, 0xeb, 0x2b, 0xf8, 0x68, 0xbe, 0x82, 0x0f, 0x22, 0x97, 0x05, 0xbb, 0xdf, 0x30, 0xf0,
	0xf1, 0x87, 0x6e, 0xc2, 0x79, 0xa6, 0x3e, 0x65, 0x62, 0x52, 0xb2, 0x1e, 0xbb, 0x57, 0x1f, 0x78,
	0x5a, 0x8e, 0xfd, 0x48, 0x27, 0xc3, 0x4b, 0xc4, 0x10, 0x47, 0xc3, 0x79, 0x29, 0xc5, 0x38, 0xfc,
	0xe0, 0x8c, 0x68, 0x3c, 0x91, 0x9f, 0x91, 0xa7, 0x90, 0x5d, 0x1a, 0x32, 0x7f, 0x9a, 0x21, 0x46,
	0xe2, 0x81, 0x03, 0xc5, 0xb2, 0x6e, 0xe9, 0x7b, 0x10, 0x16, 0xcf, 0xea, 0x16, 0xda, 0xe0, 0xb6,
	0xcd, 0xbe, 0x39, 0x08, 0xdb, 0x06, 0xa7, 0x1f, 0x60, 0x63, 0xb1, 0x24, 0xa5, 0x60, 0x33, 0x92,
	0xc3, 0xfa, 0x91, 0xb6, 0x5a, 0xdd, 0x81, 0x38, 0x15, 0xbf, 0x6d, 0xf7, 0xcd, 0xe1, 0xc6, 0x5e,
	0xf8, 0xf4, 0x02, 0xf2, 0xed, 0x92, 0xa4, 0x0c, 0x5c, 0x57, 0xbc, 0x3f, 0x2a, 0xe8, 0xd7, 0x64,
	0x8b, 0xe7, 0x5d, 0xf7, 0xef, 0x92, 0x74, 0xf7, 0xf5, 0xf3, 0xfb, 0xdd, 0x4a, 0x2d, 0x3c, 0xf2,
	0xf1, 0xaa, 0x56, 0x3c, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff, 0xfa, 0x97, 0x2a, 0x98, 0xe0, 0x00,
	0x00, 0x00,
}
